HOST = "34.234.176.173"
PORT = 8848
SNAPSHOT_RULE_DATA_ID = "nacos.snapshot.rule"
SNAPSHOT_RULE_GROUP = "DEFAULT_GROUP"

JENKINS_JMX_RELATIONSHIP_DATA_ID = "nacos.jmeter.test-plan"
JENKINS_JMX_RELATIONSHIP_GROUP = "DEFAULT_GROUP"
