HOST = "localhost"
PORT = 8848
SNAPSHOT_RULE_DATA_ID = "nacos.snapshot.rule"
SNAPSHOT_RULE_GROUP = "DEFAULT_GROUP"

JENKINS_JMX_RELATIONSHIP_DATA_ID = "jenkins.job.jmx"
JENKINS_JMX_RELATIONSHIP_GROUP = "DEFAULT_GROUP"
